apiVersion: v2
appVersion: 4.0.0
description: A Helm chart for Kubernetes
name: gigapipe
type: application
version: 0.2.0

home: https://gigapipe.com/about.html
sources:
  - https://github.com/metrico/qryn-helm

maintainers:
  - name: Lorenzo Mangani 
    email: lorenzo.mangani@gmail.com
    url: https://gigapipe.com 
  - name: raven
    email: r2w5x6@protonmail.com
    url: https://github.com/mk-raven