apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qryn-helm.fullname" . }}
  labels:
  {{- include "qryn-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
    {{- include "qryn-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "qryn-helm.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        name: {{ include "qryn-helm.fullname" . }}
        imagePullSecrets:
          - name: {{ include "helm.secretName" . }}
        env:
          {{- range $key, $val := .Values.env }}
          - name: {{ $key }}
            value: "{{ $val }}"
          {{- end }}

        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP

        livenessProbe: 
          httpGet: 
            path: /ready
            port: http
          initialDelaySeconds: 10 #Default 0 
          periodSeconds: 10 #Default 10 
          timeoutSeconds: 1 #Default 1 
          successThreshold: 1 #Default 1 
          failureThreshold: 3 #Default 3 

        resources:
          {{- toYaml .Values.resources | nindent 12 }}


      restartPolicy: Always