{{- if .Values.basicAuthPass -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: basic-auth-{{ include "qryn-helm.fullname" . }}
  namespace: {{ $.Release.Namespace }}
data:
  auth: |
    {{ .Values.basicAuthPass | b64enc }}
{{- end -}}
