apiVersion: v1
kind: Service
metadata:
  name: {{ include "gigapipe.fullname" . }}
  labels:
  {{- include "gigapipe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.type }}
  selector:
  {{- include "gigapipe.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http