{{- if and .Values.serviceMonitor.enabled .Values.service -}}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "qryn-helm.fullname" . }}
  labels:
    {{- include "qryn-helm.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - port: {{ .Values.serviceMonitor.portName | quote }}
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.serviceMonitor.scheme }}
    scheme: {{ .Values.serviceMonitor.scheme | quote }}
    {{- end }}
    {{- if .Values.serviceMonitor.tlsConfig }}
    tlsConfig:
      {{- toYaml .Values.serviceMonitor.tlsConfig | nindent 6 }}
    {{- end }}
    {{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- tpl (toYaml .Values.serviceMonitor.metricRelabelings | nindent 6) . }}
    {{- end }}
    {{- if .Values.serviceMonitor.path }}
    path: {{ .Values.serviceMonitor.path }}
    {{- end }}
    {{- if .Values.serviceMonitor.relabelings }}
    relabelings:
      {{- toYaml .Values.serviceMonitor.relabelings | nindent 6 }}
    {{- end }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace | quote }}
  selector:
    matchLabels:
        {{- include "qryn-helm.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}